#!/bin/bash
GREEN="\u001b[32m"
MAGENTA="\u001b[35m"
CYAN="\u001b[36m"
YELLOW="\033[33m"
RESET="\033[0m"
RED="\033[0;31m"

declare -A options;

# load options
for opt in $@; do 
   if [[ $opt == --* ]]; then
      options[${opt:2}]=true
   fi
done

upper() {
   echo $1 | tr '[:lower:]' '[:upper:]'
}

log() {
   declare -A levels=( ["info"]="$CYAN" ["error"]="$RED" ["action"]="$MAGENTA" )
   log_level=$1

   if [[ ${options[quiet]} == true ]] && [[ $log_level != "error" ]] ; then
      return 125 # operation canceled code
   fi

   display_level=$(upper $log_level)
   printf "${levels[$log_level]}[$display_level]$RESET ${@:2}\n\n"
}

log info "starting setup"

if [[ ${options[skip-fonts]} != true ]]; then
   log info "installing fonts"

   fonts_paths="$HOME/.local/share/fonts"
   mkdir -p $fonts_paths

   for font in ./fonts/*.ttf
   do
      log info "installing font $font"

      cp $font $fonts_paths
   done

   fc-cache -f -v
else
   log info "skip fonts install"
fi

if [[ ${options[skip-dependencies]} != true ]]; then
   log info "installing dependencies"

   declare -A dependencies=( 
      ["asdf"]="./installs/asdf"
      ["homebrew"]="./installs/brew"
      ["code"]="./installs/code"
   );
   declare -a deps_orders;

   deps_orders+=( "homebrew" )
   deps_orders+=( "asdf" )
   deps_orders+=( "code" )

   for dep in "${deps_orders[@]}"; do 
      log info "trying to install $dep"

      exists=$(which $dep)
      check_install_exit=$?

      if [ $check_install_exit -ne 0 ] ;then
         log action "running ${dependencies[$dep]} script"

         ${dependencies[$dep]}
      else
         log error "$dep already registered; skipping";
      fi
   done
else
   log info "skip dependencies install"
fi

if [[ ${options[skip-settings]} != true ]]; then
   declare -A settings=( 
      ["vscode-settings.json"]="$HOME/.config/Code/User/settings.json"
      ["keybindings.json"]="$HOME/.config/Code/User/keybindings.json"
      [".zshrc"]="$HOME/.zshrc" 
      [".gitconfig"]="$HOME/.gitconfig"
   )

   declare -a settings_orders;

   settings_orders+=( "vscode-settings.json" )
   settings_orders+=( "keybindings.json" )
   settings_orders+=( ".zshrc" )

   for setting_file in "${settings_orders[@]}"; do 
      log info "installing setting $setting_file"

      cp $setting_file ${settings[$setting_file]}
   done
else
   log info "skip dependencies install"
fi
